name: Validate Manifests
on: [push, pull_request]

jobs:
  build:
    name: Validate Manifests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@latest
      - name: Validate Against Kubernetes Schema
        run: kubeconform -kubernetes-version=1.26.1 -ignore-missing-schemas -summary -ignore-filename-pattern=falco ./**/*.yaml